name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:001

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        if: ${{ github.event_name != 'pull_request' }}
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: 'Update flake.lock'
          git-author-name: 'UpdateBot'
          git-author-email: 'github-actions[bot]@users.noreply.github.com'
          git-committer-name: 'Bonus'
          git-committer-email: 'root@bonusplay.pl'
